# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# trigger:
#     - master

variables:
  MONO_VERSION: 6_6_0
  XCODE_VERSION: 10.1

jobs:

  - job: build_macos
    displayName: Build on macOS VS4Mac

    pool:
      vmImage: macOS-10.14

    steps:
      - checkout: self
        submodules: recursive

      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
        displayName: Switch to the latest Xamarin SDK

      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: Switch to the latest Xcode

      - bash: sh ./build.sh -- --target=nuget
        displayName: Run build

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          ArtifactName: nuget
          PathtoPublish: 'output/'

      - task: NuGetCommand@2
        displayName: 'NuGet push'
        # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: push
          publishVstsFeed: 'MagisterNuGet'
          packagesToPush: output/*.nupkg 
          allowPackageConflicts: true
